### ISSUE TITLE
Bug that uses ESP_SECURE_CERT_DEV_CERT_OFFSET instead of ESP_SECURE_CERT_CA_CERT_OFFSET

### ISSUE THREAD

**Issue by mohabdallah** [espressif/esp_secure_cert_mgr#12]
https://github.com/espressif/esp_secure_cert_mgr/blob/9c9a7b465e9d1fe56ec9993da669b7ba74692155/srcs/esp_secure_cert_read.c#L443

**Comment by AdityaHPatwardhan** [comment]
@mohabdallah Thanks for the issue and the fix. I can take this up internally.
Do you want to raise a PR for this? so the contribution would be in your name.

**Comment by mohabdallah** [comment]
@AdityaHPatwardhan Yes sure, are there specific steps to follow to do so?

**Comment by AdityaHPatwardhan** [comment]
You can create a GitHub pull request for the above change.
Please find more details [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests)

**Comment by mohabdallah** [comment]
For the pull request, shall I create a pull request from a fork or you will create a branch here that I can use?

**Comment by AdityaHPatwardhan** [comment]
I think the simple steps would be
1) You fork this repository
2) You create a new branch in your fork that contains this change
3) Raise a pull request to pull your branch into the master branch of this repository.
4) After that I shall get it merged.

**Comment by mohabdallah** [comment]
Done https://github.com/espressif/esp_secure_cert_mgr/pull/14

**Comment by mohabdallah** [comment]
@AdityaHPatwardhan  Added new PR
