### ISSUE TITLE
[Question] Why was NVS format replaced with TLV format?

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp_secure_cert_mgr#2]
NVS seems like a good choice. It is already supported by ESP-IDF, and rather stable. 

NVS is likely to still be supported in 5+ years, etc.

Why did you switch to TLV? 

Thanks.

**Comment by mahavirj** [comment]
@chipweinberger 

Advantage with TLV based format is we can directly use data pointers from memory mapped partition. Please see the relevant code at:

https://github.com/espressif/esp_secure_cert_mgr/blob/adf7effbb797a62cc0ee874dfb3a009b3f36fe26/srcs/esp_secure_cert_tlv_read.c#L53-L57

If we go with the NVS based storage approach then we must create an intermediate memory copy for the credentials stored in this partition and thus increase the overall memory utilization. So, TLV format has the advantage with respect to lesser memory utilization. However, we have kept this component backward compatible with support for legacy formats too, if you would like you may enable it using:

https://github.com/espressif/esp_secure_cert_mgr/blob/adf7effbb797a62cc0ee874dfb3a009b3f36fe26/Kconfig#L10

**Comment by chipweinberger** [comment]
Thanks for the explanation!

It's very helpful.
