### ISSUE TITLE
[Question] Is there a recommended way to generate the DS peripheral's RSA private/public keys on device?

### ISSUE THREAD

**Issue by chipweinberger** [espressif/esp_secure_cert_mgr#3]
Generating on device brings a few advantages:
1. generally simpler 
2. the host PC just needs to sign the public key with the CA
3. less reliance for your build system to generate keys in "just the right way"
4. private keys never leave the device

Can you recommend a way to generate the private/public keys (Y,M,Rb,MPrime variables )*on device*? Using mbedTLS for instance?

If not, Espressif should consider adding a library to ESP-IDF which does that.

**Comment by AdityaHPatwardhan** [comment]
The recommended way is to use the Espressif [Secure Pre-provisioning service](https://www.espressif.com/en/news/Espressif_preprovisioning) to pre-provision the modules at the factory itself. In that service, the private keys are generated on the device and encrypted before the device is shipped out of the Espressif factory.

> Can you recommend a way to generate the private/public keys (Y,M,Rb,MPrime variables )on device? Using mbedTLS for instance?

The private keys can be generated on any esp device through the key generation APIs provided by cryptographic libraries like mbedTLS.
mbedTLS provides a program that demonstrates the RSA key generation, you may take a look at it [here](https://github.com/Mbed-TLS/mbedtls/blob/development/programs/pkey/rsa_genkey.c).

This component is only intended to be used for accessing the `esp_secure_cert` partition. hence we have not provided any additional code for the partition generation and opted to provide simple python interface to generate the `esp_secure_cert` partition.

**Comment by chipweinberger** [comment]
Thanks you for the link.

I will try it!

**Comment by AdityaHPatwardhan** [comment]
I think my earlier comment https://github.com/espressif/esp_secure_cert_mgr/issues/3#issuecomment-1291579054 should answer the question.
As of now, there are no plans to support generating the keys in the firmware in this repository. The exact result can currently be obtained by the python script.
I will go ahead and close the issue.
Thanks,
Aditya

**Comment by chipweinberger** [comment]
@AdityaHPatwardhan , please add functions to generate an RSA Key-Pair & ESP-DS Peripheral params on device.

Most important (RSA -> DS Params):
`esp_err_t esp_mbedtls_generate_ds_params(const mbedtls_rsa_context* rsa,  esp_ds_p_data_t* params);`

For Convenience (Create RSA):
`esp_err_t esp_mbedtls_generate_esp_ds_key_pair(mbedtls_rsa_context* out);`

For Convenience (RSA -> rrinv, mprime):   
`esp_err_t esp_mbedtls_calculate_rinv_mprime(const mbedtls_rsa_context* rsa, mbedtls_mpi* rinv, uint32_t* mprime);`

I've already done some of the code, tested working.

```
// Generate RInv & MPrime from RSA private numbers
void esp_mbedtls_calculate_rinv_mprime(const mbedtls_rsa_context* rsa, mbedtls_mpi* rinv, uint32_t* mprime)
{
    // python equivalent code:
    //
    //    key_size = private_key.key_size # in bits
    //
    //    # calculate rinv == Rb
    //    rr = 1 << (key_size * 2)
    //    rinv = rr % pub_numbers.n # RSA r inverse operand
    //
    //    # calculate MPrime
    //    a = rsa._modinv(M, 1 << 32)
    //    mprime = (a * -1) & 0xFFFFFFFF # RSA M prime operand

    // rr = 1 << (keySize * 2)
    mbedtls_mpi rr;
    mbedtls_mpi_init(&rr);
    mbedtls_mpi_lset(&rr, 1);
    mbedtls_mpi_shift_l(&rr, sizeof(pd_4096_bit_t) * 8 * 2);

    // rinv = rr % rsa.N 
    mbedtls_mpi_mod_mpi(&rinv, &rr, &N);

    // shft32 = 1 << 32
    mbedtls_mpi shft32;
    mbedtls_mpi_init(&shft32);
    mbedtls_mpi_lset(&shft32, 1);
    mbedtls_mpi_shift_l(&shft32, 32);

    // a = rsa._modinv(N, 1 << 32)
    mbedtls_mpi a;
    mbedtls_mpi_init(&a);
    mbedtls_mpi_inv_mod(&a, &N, &shft32);

    // a32 = a 
    uint32_t a32 = 0;
    mbedtls_mpi_write_binary_le(&a, (uint8_t*) &a32, sizeof(uint32_t));

    // mprime
    *mprime = ((int32_t) a32 * -1) & 0xFFFFFFFF;

    //
    // Results
    //
    printMpi(&rinv, "RInv");
    printf("mprime: 0x%x\n", *mprime);
}

void printMpi(const mbedtls_mpi* mpi, const char* name)
{
    size_t olen = 0;
    uint32_t len = MBEDTLS_MPI_MAX_SIZE * 2 + 1;
    char* pp = (char*)calloc(1, len);
    mbedtls_mpi_write_string(mpi, 16, pp, len, &olen);
    printf("%s: %s\n", name, pp);
    free(pp);
}
```
